# Generated by Django 6.1.1 on 2026-09-29 12:01

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterProblemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_and_folders', models.BooleanField(default=False)),
                ('trust_issues_vs_code', models.BooleanField(default=False)),
                ('ms_powershell_mini_forge_prompt', models.BooleanField(default=False)),
                ('starting_idle', models.BooleanField(default=False)),
                ('ms_start_app', models.BooleanField(default=False)),
                ('antivirus', models.BooleanField(default=False)),
                ('other', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyLink',
            fields=[
                ('token', models.CharField(max_length=43, primary_key=True, serialize=False)),
                ('building_number', models.CharField(max_length=10)),
                ('single_use', models.BooleanField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^s[0-9]{6}\\Z', "Student number must be a lowercase 's' followed by 6 digits.")])),
                ('username', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[a-z]+\\Z', 'Username must be lowercase letters (staff initials).')])),
                ('satisfaction', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('course_number', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[0-9]{5}\\b', 'Course must start with its 5-digit course number.')])),
                ('building_number', models.CharField(max_length=10)),
                ('workshop', models.BooleanField()),
                ('used_ai', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('student_number', ''), ('username', ''), _connector='XOR'), name='student_number_xor_username', violation_error_message='Give either a student number or a username, not both.')],
            },
        ),
    ]
